version: "3"
services:
  pyspark:
    image: "jupyter/pyspark-notebook:spark-3.3.2"
    working_dir: /home/app/
    volumes:
      - C:/docker/pysparkessencial:/home/app/
    ports:
      - 8888:8888
    networks:
      - minha-rede-master

networks:
  minha-rede-master:
